export const GET_DATA_FROM_SERVER = 'GET_DATA_FROM_SERVER';
//101 sortinimas pagal varda ir auksti
//export const SORT_CLIENT_NAME_ASC = 'SORT_CLIENT_NAME_ASC';
//export const SORT_CLIENT_NAME_DESC = 'SORT_CLIENT_NAME_DESC';
//export const SORT_CLIENT_HEIGHT_ASC = 'SORT_CLIENT_HEIGHT_ASC';
//export const SORT_CLIENT_HEIGHT_DESC = 'SORT_CLIENT_HEIGHT_DESC';

